apiVersion: v1
data:
  sample.conf: |
    This is my configuration file for Node_app
kind: ConfigMap
metadata:
  name: myapp
  namespace: pranit-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  namespace: pranit-ns
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp 
    spec:
      containers:
      - name: nodeserver
        image: thetips4you/nodeapp:latest
        ports:
        - containerPort: 3000
        volumeMounts:
          - name: testconfigmap
            mountPath: "/tmp/config" 
      volumes:
      - name: testconfigmap
        configMap:
          name: myapp   
          items:
          - key: sample.conf
            path: sample.conf
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
  namespace: pranit-ns
spec:
  selector:
    app: nodeapp 
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31111
